# Generated by ts2python version 0.7.5 on 2024-11-05 13:56:28.905808


import datetime
from typing import TypedDict, Union, List


class IStoredEmbedding(TypedDict, total=True):
    modelId: str
    embedding: List[float]


class IStoredTextRendering(TypedDict, total=True):
    modelId: str
    text: str

class IStorable:              
   id : Union[str, None]
   applicationId: str
   contextId: Union[str, None]
   userId: Union[str, None]
   created: datetime
   amended: datetime  
   className: str
   schemaVersion: float       

class IStoredChunk(IStorable):
    chunkFunctionalKey: str
    parentChunkId: Union[str, None]
    originalText: Union[str, None]
    storedEmbedding: Union[IStoredEmbedding, None]
    storedSummary: Union[IStoredTextRendering, None]
    storedTitle: Union[IStoredTextRendering, None]
    relatedChunks: Union[List[str], None]

class IStoredChunkQuerySpec(TypedDict, total=True):
    chunkFunctionalKey: str



