openapi: 3.0.0
info:
  title: Boxer API Service
  description: A simple service to retrieve AI learning content
  version: 1.0.0
servers:
  - url: ${{OPENAPI_SERVER_URL}}
    description: The Braid api server
paths:
  /api/studioforteams-boxer:
    get:
      operationId: boxer
      summary: Boxer answers questions about generative AI.
      description: Boxer answers questions about generative AI by providing a direct answer enriched with useful links from the Boxer knowledge base. 
      parameters:
        - name: question
          in: query
          description: A question about generative AI
          schema:
            type: string
          required: true
      responses:
        '200':
          description: A an array containing an answer to the question, enriched with further elements providing relevant articles.
          content:
            application/json:
              schema:
                 type: array
                 items:           
                  properties:                                  
                     summary:
                       type: string
                       description: A summary of a relevant article from the Boxer knowledge base.
                     url:
                       type: string
                       description: The URL of a relevant article from the Boxer knowledge base.                       

                       