source_patterns:
    - "*.py"
    - "*.ts"
    - "*.tsx"

skip_dirs:
    - "__pycache__"
    - "node_modules"
    - "venv"
    - ".idea"
    - ".pytest_cache"
    - ".vscode"
    - "data"    
        
skip_patterns:
    - "*.pyc"
    - "*.pyo"
    - "*.so"
    - "*.o"
    - "*.jpg"
    - "*.jpeg"
    - "*.png"
    - "*.gif"
    - "*.pdf"
    - "*.bin"
    - "*.exe"
    - "*.dll"
    - "*.class"
    - ".DS_Store"
    - ".gitignore"
    - "*.pkl"
    - "*.pyd"
    - "*.dylib"
    - "*.json"    
    - "*.gitignore"
    - "*.log"
    - "*.js"
    - "*.map"
    - "*.txt"    
    - "*.mdd"       
    - "*.vtt"       
    - "*.html"
    - "__init__.py"
