# directory_visitor_readme.py
"""
Visitor that checks if a directory needs a 'ReadMe.Salon.md' summary,
and if so, creates or updates it using a chosen summarization model.
"""

import os
from datetime import datetime
from typing import Optional
from .models.base import AIModel
from CommonPy.src.request_utilities import request_timeout

from .directory_visitor_base import DirectoryVisitor, DirectoryData
from .models.model_factory import create_model

class DirectoryVisitorForReadme(DirectoryVisitor):
    """
    Creates or updates 'ReadMe.Salon.md' by summarizing the directory's
    source files if they are newer than the existing readme.
    """
    SUMMARY_FILENAME = 'ReadMe.Salon.md'

    def __init__(self, model_type: str = "braid_api", priority: int = 1) -> None:
        """
        :param model_type: Summarisation model type: 'braid_api' or 'local_gemini'.
        """
        super().__init__(priority=priority)
        print(f"Creating model: {model_type}")
        self.driver: AIModel = create_model(model_type.lower())

    def summarise_code(self, code: str) -> Optional[str]:
        """
        Summarize source code text using the configured model driver.
        """
        return self.driver.generate_content(code, persona="CodeSummariser", 
                                      persona_intro="You are an AI assistant that summarizes code to help explain it to new developers.",
                                      length_in_words=100)

    def visit(self, directory_data: DirectoryData) -> None:
        """
        Decide whether 'ReadMe.Salon.md' should be created or updated
        based on timestamps of the source files.
        """
        if not directory_data.source_files:
            return

        readme_path = directory_data.path / self.SUMMARY_FILENAME
        readme_timestamp = 0
        if readme_path.exists():
            readme_timestamp = os.path.getmtime(readme_path)

        need_resummarize = (not directory_data.has_readme)
        for src_file in directory_data.source_files:
            if os.path.getmtime(src_file) > readme_timestamp:
                need_resummarize = True
                break

        if not need_resummarize:
            return

        new_readme = []
        for src_file in directory_data.source_files:
            try:
                with open(src_file, 'r', encoding='utf-8') as f:
                    code = f.read().rstrip()
                if len(code) > 250:  # Summarize only if file is somewhat large
                    summary = self.summarise_code(code)
                    if summary:
                        new_readme.append(f"**{src_file.name}**\n\n{summary}\n")
            except Exception as e:
                print(f"Failed to summarize {src_file}: {e}")

        if new_readme:
            # Append "Generated by Salon..." comment with preceding newline
            salon_comment = (
                f"\nGenerated by Salon from Braid Technologies, "
                f"{datetime.now().strftime('%d/%m/%Y')}"
            )

            with open(readme_path, 'w', encoding='utf-8') as f:
                f.write("\n".join(new_readme))
                f.write(salon_comment)

            print(f"Created/Updated {readme_path}")
