## file to have functions which evualate GPT-3.5 embeddings 

# Standard Library Imports
import logging
import os
import json
import sys
from logging import Logger
from typing import List, Dict, Any
import numpy as np
from numpy.linalg import norm
import datetime


import google.generativeai as genai


GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_SERVICE_ENDPOINT = "https://generativelanguage.googleapis.com"

system_instruction_prompt_eval = f"""Prompt: 
You are a professional LLM result evaluator working with responses generated by a LLM. Your role is to assess the quality and relevance of answers produced by LLM: ChatGPT-4, ensuring that they effectively address the user's concerns.

*** Instructions ***
As a result evaluator, follow these steps to assess the answers:

- Understand the Question: Carefully read the user's question to grasp the context, scope, and key concerns. This will help you determine the relevance and completeness of the response.
- Assess the Answer: Analyze the response generated by ChatGPT-4. Consider factors such as relevance, accuracy, completeness, and clarity in addressing the user's concerns. 
- Rate the Answer: Provide a score based on the following scale:
   - 1: The answer is irrelevant, incomplete, or fails to address the question.
   - 2: The answer addresses part of the question but misses key points or lacks detail.
   - 3: The answer is generally helpful but could be more precise or complete.
   - 4: The answer is excellent, directly addresses all aspects of the question, and provides clear and relevant information.


*** Response Format ***
Total rating: (Your score here)

*** Outro ***
Your main task is to ensure that Summary Generated by GPT-4 is evaluated for its relevance, clarity, and effectiveness in addressing the user's question. Use the rating scale to guide your assessments and repond strictly as per the Example Response Format.

"""
question = "How can LLM technology improve customer service in businesses?"

summary = "The article explains how LLM technology enhances customer service by automating responses, providing 24/7 support, and personalizing interactions. It covers integration with chatbots, reducing response times, and analyzing customer sentiment. Additionally, it discusses training models on specific business data for accurate, context-aware assistance."


QuestionAndSummary = f"""
Question: {question}
Summary: {summary}
"""

model = genai.GenerativeModel(
    "models/gemini-1.5-pro",
    system_instruction=system_instruction_prompt_eval,
)





response = model.generate_content(QuestionAndSummary)
print(response.text)
