# c4_generator.py
"""
Visitor that looks for 'readme.md' (case-insensitive) and subdirectories'
'readme.salon.md'. If found, it generates three mermaid-based C4 diagrams 
(C4Context, C4Container, C4Component).

This version ensures that:
1) We remove any ```mermaid fences from the generated output.
2) We strip out any <think> tags (if they appear).
3) We append a neat footer at the end of the diagram, supporting built-in
   rendering in Markdown environments (no extra fences).
"""

import os
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from CommonPy.src.request_utilities import request_timeout

from .base import DirectoryProcessor
from ..types.directory_data import DirectoryData
from ..models.model_factory import create_model
from ..models.base import AIModel
from ..core.file_handler import FileHandler
from ..prompts.prompts import (
    C4_DIAGRAMMER_PERSONA_INTRO,
    C4_CONTEXT_PROMPT,
    C4_CONTAINER_PROMPT,
    C4_COMPONENT_PROMPT
)

def append_footer(text: str) -> str:
    """
    Appends a footer line at the bottom of the diagram content.
    This is done in a way that it still renders well in Markdown
    (no fences, no extra syntax).
    """
    date_str = datetime.now().strftime('%d/%m/%Y')
    footer_line = f"%% Generated by Salon from Braid Technologies, {date_str}"
    
    # Ensure there's a blank line before the footer
    return text.rstrip() + "\n\n" + footer_line + "\n"


class C4Generator(DirectoryProcessor):
    """
    For each directory, if there's a 'readme.md' and at least one subdirectory
    with a 'readme.salon.md', we create 3 C4 diagrams in Mermaid format:
    - C4Context.Salon.md
    - C4Container.Salon.md
    - C4Component.Salon.md
    """

    def __init__(self, model_type: str = "braid_api", priority: int = 2) -> None:
        super().__init__(priority=priority)
        self.driver: AIModel = create_model(model_type.lower())
        self.file_handler = FileHandler()  # Instantiate FileHandler

    def summarise_code(self, text: str) -> Optional[str]:
        """
        Summarizes the given text using a 'C4Diagrammer' persona prompt
        or equivalent logic for local_gemini.
        """
        return self.driver.generate_content(
            text,
            persona="C4Diagrammer",
            persona_intro=C4_DIAGRAMMER_PERSONA_INTRO,
            length_in_words=1000
        )

    def visit(self, directory_data: DirectoryData) -> None:
        """
        For the current directory:
        1. Check if there's a readme.md (case-insensitive).
        2. If so, read it; then look in subdirectories for readme.salon.md.
        3. If at least one subdirectory has readme.salon.md, generate 3 mermaid-based
           C4 diagrams (Context, Container, Component).
        """
        dir_path = directory_data.path
        all_filenames = [f.name for f in directory_data.all_files]

        # Find readme.md (case-insensitive)
        readme_file_name = next((f for f in all_filenames if f.lower() == 'readme.md'), None)
        if not readme_file_name:
            return  # No readme, do nothing

        # Read its content
        readme_file_path = dir_path / readme_file_name
        readme_text = self.file_handler.read_file(readme_file_path)
        if not readme_text:
            return

        # Check subdirectories for readme.salon.md
        have_readme_and_salon_files = False
        for sub_d in dir_path.iterdir():
            if sub_d.is_dir() and sub_d.name.lower() != 'test':
                try:
                    for f in sub_d.iterdir():
                        if f.is_file() and f.name.lower() == 'readme.salon.md':
                            have_readme_and_salon_files = True
                            readme_salon_text = self.file_handler.read_file(f)
                            if readme_salon_text:
                                readme_text += "\n\n" + readme_salon_text
                except Exception as e2:
                    print(f"Error scanning subdirectory {sub_d}: {e2}")

        if not have_readme_and_salon_files:
            return

        print(f"Found 'readme.md' + 'ReadMe.Salon.md' in subdirectories of: {dir_path}")

        # Generate the 3 diagrams:

        # 1. C4Context
        prompt_context = C4_CONTEXT_PROMPT + readme_text
        summary = self.summarise_code(prompt_context)
        if summary:
            # append footer
            summary = append_footer(summary)
            self.file_handler.write_file_version(dir_path, 'C4Context.Salon.md', summary)

        # 2. C4Container
        prompt_container = C4_CONTAINER_PROMPT + readme_text
        summary = self.summarise_code(prompt_container)
        if summary:
            summary = append_footer(summary)
            self.file_handler.write_file_version(dir_path, 'C4Container.Salon.md', summary)

        # 3. C4Component
        prompt_component = C4_COMPONENT_PROMPT + readme_text
        summary = self.summarise_code(prompt_component)
        if summary:
            summary = append_footer(summary)
            self.file_handler.write_file_version(dir_path, 'C4Component.Salon.md', summary)
