# directory_visitor_readme.py
"""
Visitor that checks if a directory needs a 'ReadMe.Salon.md' summary,
and if so, creates or updates it using a chosen summarization model.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional
from ..models.base import AIModel
from CommonPy.src.request_utilities import request_timeout

from .base import DirectoryProcessor
from ..types.directory_data import DirectoryData
from ..models.model_factory import create_model
from ..core.file_handler import FileHandler
from ..prompts.prompts import CODE_SUMMARIZER_PERSONA_INTRO

class ReadmeGenerator(DirectoryProcessor):
    """
    Creates or updates 'ReadMe.Salon.md' by summarizing the directory's
    source files if they are newer than the existing readme.
    """
    SUMMARY_FILENAME = 'ReadMe.Salon.md'

    def __init__(self, model_type: str = "braid_api", priority: int = 1) -> None:
        super().__init__(priority=priority)
        print(f"Creating model: {model_type}")
        self.driver: AIModel = create_model(model_type.lower())
        self.file_handler = FileHandler()  # Instantiate FileHandler

    def summarise_code(self, code: str) -> Optional[str]:
        """
        Summarize source code text using the configured model driver.
        """
        return self.driver.generate_content(code, persona="CodeSummariser",
                                            persona_intro= CODE_SUMMARIZER_PERSONA_INTRO,
                                            length_in_words=100)

    def visit(self, directory_data: DirectoryData) -> Path:
        """
        Decide whether 'ReadMe.Salon.md' should be created or updated
        based on timestamps of the source files.
        """
        if not directory_data.source_files:
            return

        readme_path = directory_data.path / self.SUMMARY_FILENAME
        readme_timestamp = 0
        if readme_path.exists():
            readme_timestamp = os.path.getmtime(readme_path)

        need_resummarize = (not directory_data.has_readme)
        for src_file in directory_data.source_files:
            if os.path.getmtime(src_file) > readme_timestamp:
                need_resummarize = True
                break

        if not need_resummarize:
            return

        new_readme = []
        for src_file in directory_data.source_files:
            code = self.file_handler.read_file(src_file) # Use FileHandler to read files
            if code and len(code) > 250:  # Summarize only if file is somewhat large
                summary = self.summarise_code(code)
                if summary:
                    if src_file.name ==  self.SUMMARY_FILENAME:
                        new_readme.append(f"**Directory {src_file.parent.name}**\n\n{summary}\n")
                    else:
                        new_readme.append(f"**{src_file.name}**\n\n{summary}\n")

        if new_readme:
            salon_comment = (
                f"\nGenerated by Salon from Braid Technologies, "
                f"{datetime.now().strftime('%d/%m/%Y')}"
            )
            content = "\n".join(new_readme) + salon_comment
            self.file_handler.write_file_version(directory_data.path, self.SUMMARY_FILENAME, content) # Use FileHandler to write files
            print(f"Created/Updated {readme_path}")   
            return readme_path
        return None