import os
import pytest
from pathlib import Path
import tempfile
import shutil
from unittest.mock import patch, MagicMock, call, ANY
from datetime import datetime

from Salon.src.directory_processor.c4_generator import C4Generator, append_footer
from Salon.src.types.directory_data import DirectoryData
from Salon.src.models.base import AIModel
from Salon.src.core.file_handler import FileHandler


@pytest.fixture
def mock_driver():
    """Fixture to create a mock AI model driver."""
    mock = MagicMock(spec=AIModel)
    mock.generate_content.return_value = "```mermaid\ngraph TD\nA[Component A] --> B[Component B]\n```"
    return mock


@pytest.fixture
def mock_file_handler():
    """Fixture to create a mock FileHandler."""
    mock = MagicMock(spec=FileHandler)
    mock.read_file.return_value = "# Test Readme\nThis is a test."
    mock.write_file_version.return_value = Path("/test/output.md")
    return mock


@pytest.fixture
def c4_generator(mock_driver, mock_file_handler):
    """Fixture to create a C4Generator with mocked dependencies."""
    with patch('Salon.src.directory_processor.c4_generator.create_model', return_value=mock_driver):
        generator = C4Generator(model_type="test_model", priority=1)
        generator.file_handler = mock_file_handler
        return generator


@pytest.fixture
def temp_dir():
    """Fixture to create and clean up a temporary directory structure for testing."""
    temp_dir = tempfile.mkdtemp()
    base_dir = Path(temp_dir)
    
    # Create main readme.md
    with open(base_dir / "readme.md", 'w', encoding='utf-8') as f:
        f.write("# Test Project\nThis is the main readme.")
    
    # Create subdirectory with readme.salon.md
    sub_dir = base_dir / "module1"
    sub_dir.mkdir()
    with open(sub_dir / "readme.salon.md", 'w', encoding='utf-8') as f:
        f.write("# Module 1\nThis is a component.")
    
    # Create another subdirectory without readme.salon.md
    (base_dir / "module2").mkdir()
    
    # Create a test directory to be ignored
    test_dir = base_dir / "test"
    test_dir.mkdir()
    
    yield base_dir
    shutil.rmtree(temp_dir)


class TestAppendFooter:
    """Tests for the append_footer utility function."""
    
    def test_append_footer_adds_formatted_line(self):
        """Test that append_footer adds a properly formatted footer line."""
        input_text = "This is a test diagram\nwith multiple lines."
        result = append_footer(input_text)
        
        # Check result contains the original text
        assert input_text in result
        
        # Check for footer format and content
        assert "%% Generated by Salon from Braid Technologies" in result
        assert datetime.now().strftime('%d/%m/%Y') in result
        
        # Check positioning and spacing
        lines = result.split("\n")
        assert lines[-2].startswith("%%")  # Footer should be the second-to-last line
        assert lines[-1] == ""  # Last line should be empty
        assert lines[-3] == ""  # There should be a blank line before the footer

    def test_append_footer_handles_trailing_whitespace(self):
        """Test that append_footer correctly handles input with trailing whitespace."""
        input_text = "Diagram with trailing spaces   \n  \n"
        result = append_footer(input_text)
        
        # Should have exactly one blank line between content and footer
        assert not result.startswith("\n\n")
        assert "Diagram with trailing spaces" in result
        assert "\n\n%% Generated by" in result


class TestC4Generator:
    """Tests for the C4Generator class."""
    
    def test_init_default_values(self):
        """Test that C4Generator initializes with default values."""
        with patch('Salon.src.directory_processor.c4_generator.create_model') as mock_create_model:
            mock_model = MagicMock()
            mock_create_model.return_value = mock_model
            
            generator = C4Generator()
            
            assert generator.priority == 2
            mock_create_model.assert_called_once_with("braid_api")
            assert isinstance(generator.file_handler, FileHandler)

    def test_init_custom_values(self):
        """Test that C4Generator initializes with custom values."""
        with patch('Salon.src.directory_processor.c4_generator.create_model') as mock_create_model:
            mock_model = MagicMock()
            mock_create_model.return_value = mock_model
            
            generator = C4Generator(model_type="custom_model", priority=5)
            
            assert generator.priority == 5
            mock_create_model.assert_called_once_with("custom_model")

    def test_summarise_code(self, c4_generator, mock_driver):
        """Test the summarise_code method correctly calls the driver."""
        input_text = "# Test code\ndef hello(): pass"
        result = c4_generator.summarise_code(input_text)
        
        mock_driver.generate_content.assert_called_once_with(
            input_text,
            persona="C4Diagrammer",
            persona_intro=ANY,  # Use ANY instead of a specific type check
            length_in_words=1000
        )
        assert result == "```mermaid\ngraph TD\nA[Component A] --> B[Component B]\n```"

    def test_visit_no_readme(self, c4_generator):
        """Test that visit does nothing when there's no readme.md."""
        mock_dir_data = MagicMock(spec=DirectoryData)
        # Properly set up the path attribute
        mock_dir_data.path = MagicMock()
        mock_dir_data.all_files = []
        
        c4_generator.visit(mock_dir_data)
        
        # No files should be read or written
        c4_generator.file_handler.read_file.assert_not_called()
        c4_generator.file_handler.write_file_version.assert_not_called()

    def test_visit_with_readme_no_salon(self, c4_generator, mock_file_handler):
        """Test that visit does nothing when there's a readme.md but no subdirectories with readme.salon.md."""
        # Create a mock directory data
        mock_dir_data = MagicMock(spec=DirectoryData)
        mock_path = MagicMock()
        mock_dir_data.path = mock_path
        
        # Create a mock readme file
        mock_readme = MagicMock()
        mock_readme.name = "readme.md"
        mock_dir_data.all_files = [mock_readme]
        
        # Setup subdirectory without readme.salon.md
        sub_dir = MagicMock()
        sub_dir.is_dir.return_value = True
        sub_dir.name = "module1"
        sub_dir.iterdir.return_value = []
        
        # Setup the directory structure
        mock_path.iterdir.return_value = [sub_dir]
        
        c4_generator.visit(mock_dir_data)
        
        # Should have read the main readme but not written any files
        assert mock_file_handler.read_file.call_count == 1
        mock_file_handler.write_file_version.assert_not_called()

    @patch('builtins.print')
    def test_visit_with_readme_and_salon(self, mock_print, c4_generator, mock_file_handler, mock_driver):
        """Test that visit correctly generates diagrams when there's a readme.md and subdirectories with readme.salon.md."""
        # Setup directory data with proper mocking
        mock_dir_data = MagicMock(spec=DirectoryData)
        mock_path = MagicMock()
        mock_dir_data.path = mock_path
        
        # Create a mock readme file
        mock_readme = MagicMock()
        mock_readme.name = "readme.md"
        mock_dir_data.all_files = [mock_readme]
        
        # Setup a subdirectory with readme.salon.md
        salon_file = MagicMock()
        salon_file.is_file.return_value = True
        salon_file.name = "readme.salon.md"
        
        sub_dir = MagicMock()
        sub_dir.is_dir.return_value = True
        sub_dir.name = "module1"
        sub_dir.iterdir.return_value = [salon_file]
        
        # Setup the directory structure
        mock_path.iterdir.return_value = [sub_dir]
        
        # Run the method
        c4_generator.visit(mock_dir_data)
        
        # Verify correct behavior
        assert mock_print.call_count == 1  # Should print the found message
        assert mock_file_handler.read_file.call_count == 2  # Should read main readme and salon readme
        
        # Should generate and write 3 files (Context, Container, Component)
        assert mock_driver.generate_content.call_count == 3
        assert mock_file_handler.write_file_version.call_count == 3
        
        # Check that the right files were written
        write_calls = mock_file_handler.write_file_version.call_args_list
        assert call(mock_path, 'C4Context.Salon.md', ANY) == write_calls[0]
        assert call(mock_path, 'C4Container.Salon.md', ANY) == write_calls[1]
        assert call(mock_path, 'C4Component.Salon.md', ANY) == write_calls[2]

    def test_visit_with_test_directory_excluded(self, c4_generator, mock_file_handler):
        """Test that test directories are excluded from processing."""
        # Setup directory data with proper mocking
        mock_dir_data = MagicMock(spec=DirectoryData)
        mock_path = MagicMock()
        mock_dir_data.path = mock_path
        
        # Create a mock readme file
        mock_readme = MagicMock()
        mock_readme.name = "readme.md"
        mock_dir_data.all_files = [mock_readme]
        
        # Setup a test subdirectory
        test_dir = MagicMock()
        test_dir.is_dir.return_value = True
        test_dir.name = "test"
        
        # Setup the directory structure
        mock_path.iterdir.return_value = [test_dir]
        
        # Run the method
        c4_generator.visit(mock_dir_data)
        
        # Should read the main readme but not process test directory or write any files
        assert mock_file_handler.read_file.call_count == 1
        mock_file_handler.write_file_version.assert_not_called()

    def test_visit_handles_exception_in_subdirectory(self, c4_generator, mock_file_handler):
        """Test that visit handles exceptions when scanning subdirectories."""
        # Setup directory data with proper mocking
        mock_dir_data = MagicMock(spec=DirectoryData)
        mock_path = MagicMock()
        mock_dir_data.path = mock_path
        
        # Create a mock readme file
        mock_readme = MagicMock()
        mock_readme.name = "readme.md"
        mock_dir_data.all_files = [mock_readme]
        
        # Setup a subdirectory that raises an exception
        sub_dir = MagicMock()
        sub_dir.is_dir.return_value = True
        sub_dir.name = "module1"
        sub_dir.iterdir.side_effect = Exception("Access denied")
        
        # Setup the directory structure
        mock_path.iterdir.return_value = [sub_dir]
        
        # Run the method - should not raise an exception
        with patch('builtins.print') as mock_print:
            c4_generator.visit(mock_dir_data)
            
            # Should have caught and printed the exception
            assert "Error scanning subdirectory" in mock_print.call_args[0][0]
        
        # Should read the main readme but not write any files
        assert mock_file_handler.read_file.call_count == 1
        mock_file_handler.write_file_version.assert_not_called()

    def test_visit_integration_with_real_files(self, temp_dir):
        """Integration test using real files in a temporary directory."""
        # Create a real C4Generator with mocked driver
        mock_driver = MagicMock(spec=AIModel)
        mock_driver.generate_content.return_value = "graph TD\nA[System] --> B[External System]"
        
        with patch('Salon.src.directory_processor.c4_generator.create_model', return_value=mock_driver):
            generator = C4Generator()
            
            # Create directory data
            dir_data = DirectoryData(path=temp_dir)
            dir_data.all_files = list(temp_dir.glob("*"))
            
            # Run the method
            generator.visit(dir_data)
            
            # Verify files were created
            assert (temp_dir / "C4Context.Salon.md").exists()
            assert (temp_dir / "C4Container.Salon.md").exists()
            assert (temp_dir / "C4Component.Salon.md").exists()
            
            # Check content of one of the files
            with open(temp_dir / "C4Context.Salon.md", 'r') as f:
                content = f.read()
                assert "graph TD" in content
                assert "%% Generated by Salon from Braid Technologies" in content
