# Generated by ts2python version 0.7.5 on 2024-11-05 13:56:28.905808
"""
Defines several TypedDict and class structures for storing and querying
data related to embeddings and text renderings.

Classes:
    IStoredEmbedding: A TypedDict representing an embedding with a model ID
        and a list of float values.
    IStoredTextRendering: A TypedDict representing a text rendering with a
        model ID and text content.
    IStorable: A base class with common attributes for storable entities,
        including identifiers, timestamps, and schema version.
    IStoredChunk: Inherits from IStorable, representing a chunk of data with
        additional attributes for functional key, parent chunk ID, original
        text, and related stored embeddings and text renderings.
    IStoredChunkQuerySpec: A TypedDict for specifying query parameters for
        stored chunks, including a functional key.
"""

import datetime
from typing import TypedDict, Union, List



class IStoredEmbedding(TypedDict, total=True):
    """
    A TypedDict representing a stored embedding.

    Attributes:
       modelId (str): The identifier for the model associated with the embedding.
       embedding (List[float]): A list of float values representing the embedding.
    """
    modelId: str
    embedding: List[float]


class IStoredTextRendering(TypedDict, total=True):
    """
    A TypedDict representing a text rendering.

    Attributes:
       modelId (str): The identifier for the model associated with the text rendering.
       text (str): The content of the text rendering.
    """
    modelId: str
    text: str


class IStorable:
    """
    A base class for storable entities with common attributes.

    Attributes:
     id (Union[str, None]): The unique identifier for the entity, which can be None.
     applicationId (str): The identifier for the application associated with the entity.
     contextId (Union[str, None]): The identifier for the context, which can be None.
     userId (Union[str, None]): The identifier for the user, which can be None.
     created (datetime): The timestamp when the entity was created.
     amended (datetime): The timestamp when the entity was last modified.
     className (str): The name of the class.
     schemaVersion (float): The version of the schema used by the entity.
    """
    id: Union[str, None]
    applicationId: str
    contextId: Union[str, None]
    userId: Union[str, None]
    created: datetime
    amended: datetime
    className: str
    schemaVersion: float


class IStoredChunk(IStorable):
    """
    Represents a stored chunk of data with various attributes.

    Attributes:
    chunkFunctionalKey (str): A key used to identify the chunk functionally.
    parentChunkId (Union[str, None]): The ID of the parent chunk, if any.
    originalText (Union[str, None]): The original text content of the chunk.
    storedEmbedding (Union[IStoredEmbedding, None]): An optional stored embedding associated with the chunk.
    storedSummary (Union[IStoredTextRendering, None]): An optional stored summary text rendering.
    storedTitle (Union[IStoredTextRendering, None]): An optional stored title text rendering.
    relatedChunks (Union[List[str], None]): A list of IDs of related chunks, if any.
    """
    chunkFunctionalKey: str
    parentChunkId: Union[str, None]
    originalText: Union[str, None]
    storedEmbedding: Union[IStoredEmbedding, None]
    storedSummary: Union[IStoredTextRendering, None]
    storedTitle: Union[IStoredTextRendering, None]
    relatedChunks: Union[List[str], None]


class IStoredChunkQuerySpec(TypedDict, total=True):
    """
    A TypedDict for specifying query parameters for stored chunks.

    Attributes:
     chunkFunctionalKey (str): The functional key used to identify the chunk.
    """
    chunkFunctionalKey: str
