"""
Defines several class structures for storing and querying
data related to embeddings and text renderings.

Classes:
    IStoredPage: Inherits from IStorable, representing a chunk of data with
        an additional attributes for html.
"""

# Generated by ts2python version 0.7.5 on 2024-11-05 13:56:28.905808
# pylint: disable=invalid-name

from typing import Union
from .storable_types import IStorable

class IStoredPage(IStorable):
    """
    Represents a stored chunk of data with various attributes.

    Attributes:
    html (Union[str, None]): Html content of the page, if any.
    """
    html: Union[str, None]

    def __init__(self, other=None):
        super().__init__(other)

        if other:
            self.html = other.html
        else:
            self.html = None

