"""
Defines several class structures for storing and querying data.

Classes:
    IStorable: A base class with common attributes for storable entities,
        including identifiers, timestamps, and schema version.
"""
# Generated by ts2python version 0.7.5 on 2024-11-05 13:56:28.905808
# pylint: disable=invalid-name

from typing import Union

class IStorable:
    """
    A base class for storable entities with common attributes.

    Attributes:
     id (Union[str, None]): The unique identifier for the entity, which can be None.
     applicationId (str): The identifier for the application associated with the entity.
     contextId (Union[str, None]): The identifier for the context, which can be None.
     functionalSearchKey (str): A key used to identify the chunk functionally.  Can be None.
     userId (Union[str, None]): The identifier for the user, which can be None.
     created (datetime): The timestamp when the entity was created.
     amended (datetime): The timestamp when the entity was last modified.
     className (str): The name of the class.
     schemaVersion (str): The version of the schema used by the entity.
    """
    id: Union[str, None]
    applicationId: str
    contextId: Union[str, None]
    functionalSearchKey: Union[str, None]
    userId: Union[str, None]
    created: str
    amended: str
    className: str
    schemaVersion: str

    def __init__(self, other=None):
        if other:
            self.id = other.id
            self.applicationId = other.applicationId
            self.contextId = other.contextId
            self.functionalSearchKey = other.functionalSearchKey
            self.userId = other.userId
            self.created = other.created
            self.amended = other.amended
            self.className = other.className
            self.schemaVersion = other.schemaVersion
        else:
            self.id = None
            self.applicationId = None
            self.contextId = None
            self.functionalSearchKey = None
            self.userId = None
            self.created = None
            self.amended = None
            self.className = None
            self.schemaVersion = None

class IStorableQuerySpec:
    """
    A class for specifying query parameters for storables.

    Attributes:
     id (str): The primary key used to identify the chunk.
     functionalSearchKey (str) if id in None, functional key can be used.
    """
    id: str
    functionalSearchKey: str

    def __init__(self, other=None):
        if other:
            self.id = other.id
            self.functionalSearchKey = other.functionalSearchKey
        else:
            self.id = None
            self.functionalSearchKey = None


class IStorableOperationResult:
    """
    Defines the results of a storable operation - true or false.
    """

    ok: bool

    def __init__(self, other=None):
        if other:
            self.ok = other.ok
        else:
            self.ok = None
